from __future__ import annotations

import argparse
import copy
import json
import subprocess
from datetime import datetime
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover
    import tomli as tomllib


ROOT = Path(__file__).resolve().parents[1]
ARTIFACT_ROOT = ROOT / "artifacts" / "b1"
BACKTEST_ENGINE_DIR = ROOT / "backtest-engine"
DEFAULT_RULE_CONFIG = ROOT / "backtest-engine" / "crates" / "b1" / "config.toml"
DEFAULT_ML_CONFIG = ROOT / "backtest-engine" / "crates" / "b1" / "config_ml.toml"


def timestamp_ms_token() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S_%f")[:-3]


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict]:
    if not path.exists():
        return []
    rows = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def read_toml(path: Path) -> dict:
    return tomllib.loads(path.read_text(encoding="utf-8"))


def format_toml_value(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value:.12g}"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"不支持的 TOML 值类型: {type(value).__name__}")


def build_b1_config_overrides(args: argparse.Namespace) -> dict[str, object]:
    overrides: dict[str, object] = {}
    if args.start_date is not None:
        overrides["backtest.start_date"] = args.start_date
    if args.end_date is not None:
        overrides["backtest.end_date"] = args.end_date
    if args.max_hold_days is not None:
        overrides["backtest.max_hold_days"] = args.max_hold_days
    if args.max_daily_buys is not None:
        overrides["backtest.max_daily_buys"] = args.max_daily_buys
    if args.sort_field is not None:
        overrides["backtest.sort_field"] = args.sort_field
    if args.sort_ascending is not None:
        overrides["backtest.sort_ascending"] = args.sort_ascending
    return overrides


def build_effective_config(
    base_config_path: Path,
    output_path: Path,
    overrides: dict[str, object],
) -> Path:
    base_config = read_toml(base_config_path)
    effective_config = copy.deepcopy(base_config)

    for dotted_key, value in overrides.items():
        section, key = dotted_key.split(".", 1)
        if section not in effective_config:
            raise KeyError(f"配置缺少 section: {section}")
        if key not in effective_config[section]:
            raise KeyError(f"配置缺少 key: {dotted_key}")
        effective_config[section][key] = value

    section_order = [
        "backtest",
        "stop_loss",
        "take_profit",
        "weak_performance",
        "trailing_stop",
        "costs",
    ]
    lines = [
        "# Auto-generated by scripts/b1_backtest.py",
        f"# Base config: {base_config_path.as_posix()}",
    ]
    if overrides:
        lines.append("# Overrides:")
        for dotted_key, value in overrides.items():
            lines.append(f"#   {dotted_key} = {value}")
    else:
        lines.append("# Overrides: none")
    lines.append("")

    for section in section_order:
        if section not in effective_config:
            continue
        lines.append(f"[{section}]")
        for key, value in effective_config[section].items():
            lines.append(f"{key} = {format_toml_value(value)}")
        lines.append("")

    output_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return output_path


def resolve_signal_input(path_str: str) -> tuple[Path, Path]:
    path = Path(path_str).expanduser()
    if not path.is_absolute():
        path = (ROOT / path).resolve()
    else:
        path = path.resolve()

    if path.is_dir():
        meta_path = path / "signal.meta.json"
        parquet_path = path / "signal.parquet"
    elif path.suffix.lower() == ".json":
        meta_path = path
        meta = read_json(meta_path)
        parquet_rel = meta.get("signal_path") or meta.get("canonical_signal_path") or "signal.parquet"
        parquet_path = (meta_path.parent / parquet_rel).resolve()
    else:
        parquet_path = path
        meta_path = parquet_path.with_name("signal.meta.json")

    if not meta_path.exists():
        raise FileNotFoundError(f"signal.meta.json 不存在: {meta_path}")
    if not parquet_path.exists():
        raise FileNotFoundError(f"signal.parquet 不存在: {parquet_path}")
    return meta_path, parquet_path


def choose_index(items: list[str], title: str) -> int:
    print(f"\n{title}")
    for idx, item in enumerate(items, start=1):
        print(f"  {idx}. {item}")
    while True:
        choice = input("输入编号: ").strip()
        if choice.isdigit():
            value = int(choice)
            if 1 <= value <= len(items):
                return value - 1
        print("无效输入，请重试。")


def describe_b1_meta(meta: dict) -> str:
    source = meta.get("signal_source") or meta.get("seed_col") or "na"
    model_name = meta.get("model_name") or "na"
    label = meta.get("label") or "na"
    feature_set_name = meta.get("feature_set_name") or meta.get("feature_mode") or "na"
    return (
        f"source={source}, model={model_name}, "
        f"label={label}, feature_set={feature_set_name}"
    )


def resolve_default_config_for_meta(meta: dict) -> Path:
    is_rule_signal = (
        meta.get("feature_mode") == "rule"
        or meta.get("signal_source") == "rule_wmacd"
        or meta.get("model_name") == "wmacd_rule"
    )
    return DEFAULT_RULE_CONFIG if is_rule_signal else DEFAULT_ML_CONFIG


def pick_train_run() -> Path:
    train_dirs = sorted(
        [p for p in ARTIFACT_ROOT.iterdir() if p.is_dir() and (p / "signals.jsonl").exists()],
        key=lambda p: p.name,
        reverse=True,
    )
    if not train_dirs:
        raise FileNotFoundError("未找到任何包含 signals.jsonl 的 B1 train run 目录")

    display = []
    for train_dir in train_dirs:
        signals = read_jsonl(train_dir / "signals.jsonl")
        train_meta_path = train_dir / "train.meta.json"
        train_meta = read_json(train_meta_path) if train_meta_path.exists() else {}
        display.append(
            f"{train_dir.name}  ({describe_b1_meta(train_meta)}, signals={len(signals)})"
        )
    return train_dirs[choose_index(display, "选择 B1 train run")]


def pick_signal_meta(train_dir: Path) -> Path:
    signals_index = train_dir / "signals.jsonl"
    rows = read_jsonl(signals_index)
    if not rows:
        raise FileNotFoundError(f"{signals_index} 中没有 signal 记录")

    rows = sorted(rows, key=lambda r: r.get("signal_id", ""), reverse=True)
    display = []
    resolved_meta_paths = []
    for row in rows:
        signal_id = row.get("signal_id", "unknown")
        signal_meta_path = train_dir / row["signal_meta_path"]
        display.append(f"{signal_id}  ({describe_b1_meta(row)})")
        resolved_meta_paths.append(signal_meta_path.resolve())
    return resolved_meta_paths[choose_index(display, f"选择 signal ({train_dir.name})")]


def run_b1_backtest(
    signal_meta_path: Path,
    signal_parquet_path: Path,
    config_path: Path,
    release: bool,
    config_overrides: dict[str, object],
) -> int:
    signal_dir = signal_meta_path.parent
    backtest_dir = signal_dir / "backtests" / timestamp_ms_token()
    backtest_dir.mkdir(parents=True, exist_ok=True)
    effective_config_path = build_effective_config(
        base_config_path=config_path,
        output_path=backtest_dir / "effective.config.toml",
        overrides=config_overrides,
    )

    cmd = ["cargo", "run", "-p", "bt-b1"]
    if release:
        cmd.append("--release")
    cmd.extend(
        [
            "--",
            "--data",
            str(signal_parquet_path),
            "--config",
            str(effective_config_path),
            "--output-dir",
            str(backtest_dir),
        ]
    )

    print("\n即将运行:")
    print(f"  Signal Meta: {signal_meta_path}")
    print(f"  Signal File: {signal_parquet_path}")
    print(f"  Output Dir:  {backtest_dir}")
    print(f"  Base Config: {config_path}")
    print(f"  Effective:   {effective_config_path}")
    if config_overrides:
        print("  Overrides:")
        for dotted_key, value in config_overrides.items():
            print(f"    - {dotted_key} = {value}")

    result = subprocess.run(cmd, cwd=BACKTEST_ENGINE_DIR)
    if result.returncode == 0:
        print("\n回测完成:")
        print(f"  {backtest_dir / 'report.txt'}")
        print(f"  {backtest_dir / 'report.json'}")
        print(f"  {effective_config_path}")
    return result.returncode


def main() -> int:
    parser = argparse.ArgumentParser(description="B1 signal backtest helper")
    parser.add_argument("signal", nargs="?", help="signal.meta.json / signal.parquet / signal directory")
    parser.add_argument("--pick", action="store_true", help="交互式选择 train run 和 signal")
    parser.add_argument(
        "--config",
        help="B1 config.toml 路径；不传时根据 signal 自动选择 rule=config.toml / ml=config_ml.toml",
    )
    parser.add_argument("--debug", action="store_true", help="使用 debug 构建而非 release")
    parser.add_argument("--start-date", help="覆盖 backtest.start_date，例如 2025-01-05")
    parser.add_argument("--end-date", help="覆盖 backtest.end_date")
    parser.add_argument("--max-hold-days", type=int, help="覆盖 backtest.max_hold_days")
    parser.add_argument("--max-daily-buys", type=int, help="覆盖 backtest.max_daily_buys")
    parser.add_argument("--sort-field", help="覆盖 backtest.sort_field")
    parser.add_argument(
        "--sort-ascending",
        choices=["true", "false"],
        help="覆盖 backtest.sort_ascending",
    )
    args = parser.parse_args()

    if args.sort_ascending is not None:
        args.sort_ascending = args.sort_ascending == "true"

    if args.signal:
        signal_meta_path, signal_parquet_path = resolve_signal_input(args.signal)
    else:
        train_dir = pick_train_run()
        signal_meta_path = pick_signal_meta(train_dir)
        signal_meta_path, signal_parquet_path = resolve_signal_input(str(signal_meta_path))

    signal_meta = read_json(signal_meta_path)
    if args.config:
        config_path = Path(args.config).expanduser()
        if not config_path.is_absolute():
            config_path = (ROOT / config_path).resolve()
        else:
            config_path = config_path.resolve()
    else:
        config_path = resolve_default_config_for_meta(signal_meta)

    config_overrides = build_b1_config_overrides(args)

    return run_b1_backtest(
        signal_meta_path=signal_meta_path,
        signal_parquet_path=signal_parquet_path,
        config_path=config_path,
        release=not args.debug,
        config_overrides=config_overrides,
    )


if __name__ == "__main__":
    raise SystemExit(main())
