from __future__ import annotations

RAW_EXECUTION_STATUS = {
    "generated_at": "2026-05-29 14:43:11",
    "scope": "Core AMV raw-execution ground truth rerun",
    "price_basis": "raw_ohlc_pre_close for all new artifacts",
    "runs": [
        {
            "name": "ref_p2_6td",
            "group": "core",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143432_reference_p2_k0p5_b0_c0_r0/backtests/6td_static_strict_top3_no_stop_rawexec_20260529_143432_reference_p2_k0p5_b0_c0_r0",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 145.10,
            "gross_return_pct": 199.41,
            "max_drawdown_pct": 18.97,
            "win_rate_pct": 50.36,
            "total_trades": 274,
        },
        {
            "name": "p3_6td",
            "group": "core",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143434_candidate_p3_k0p5_b0_c0_r0/backtests/6td_static_strict_top3_no_stop_rawexec_20260529_143434_candidate_p3_k0p5_b0_c0_r0",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 172.37,
            "gross_return_pct": 227.44,
            "max_drawdown_pct": 13.53,
            "win_rate_pct": 51.82,
            "total_trades": 274,
        },
        {
            "name": "context_combo_6td",
            "group": "core",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143517_p3_ctx_sectormix1020_linear_b0p4_sp0p02_medium128_linear_t0p5_mp0p03_rel20_under0/backtests/6td_static_strict_top3_no_stop_rawexec_20260529_143517_p3_ctx_sectormix1020_linear_b0p4_sp0p02_medium128_linear_t0p5_mp0p03_rel20_under0",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 238.54,
            "gross_return_pct": 299.22,
            "max_drawdown_pct": 14.03,
            "win_rate_pct": 54.01,
            "total_trades": 274,
        },
        {
            "name": "pb3_gated_rolling",
            "group": "pullback",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143548_pullback_p0_k0_pb3_cp1_rv0/backtests/6td_rolling21_refill_top10_no_stop_rawexec_20260529_143548_pullback_p0_k0_pb3_cp1_rv0",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 80.55,
            "gross_return_pct": 100.91,
            "max_drawdown_pct": 11.75,
            "win_rate_pct": 51.32,
            "total_trades": 1062,
        },
        {
            "name": "limit_first_board_5td",
            "group": "limit_ecology",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143644_limit_first_board_pullback/backtests/5td_static_strict_top3_no_stop_rawexec_20260529_143644_limit_first_board_pullback",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 130.95,
            "gross_return_pct": 187.27,
            "max_drawdown_pct": 45.38,
            "win_rate_pct": 50.33,
            "total_trades": 306,
        },
        {
            "name": "limit_weakgate_5td",
            "group": "limit_ecology",
            "backtest_dir": "artifacts/amv_static_sleeve_signals/20260529_143647_limit_first_board_pullback_weakgate/backtests/5td_static_strict_top3_no_stop_rawexec_20260529_143647_limit_first_board_pullback_weakgate",
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 155.04,
            "gross_return_pct": 205.10,
            "max_drawdown_pct": 34.12,
            "win_rate_pct": 52.73,
            "total_trades": 256,
        },
    ],
    "interpretation": {
        "core": "Raw execution materially reduces static Ref/P3/context returns, but the context combo remains the strongest of the core static candidates.",
        "pb3": "PB3 gated rolling return is lower under raw execution than the previous adjusted-execution allocation diagnostic input; it still needs portfolio-level re-evaluation.",
        "limit_ecology": "First-board pullback event sleeve loses most of its adjusted-execution appeal under raw execution; weak-window variants are not allocation-ready.",
    },
}

P3_RAW_VS_ADJUSTED_ATTRIBUTION = {
    "report_name": "amv_p3_raw_vs_adjusted_trade_attribution",
    "summary": {
        "adjusted": {
            "execution_price_basis": "adjusted_legacy",
            "total_return_pct": 201.69,
            "gross_return_pct": 260.86,
            "max_drawdown_pct": 13.52,
            "win_rate_pct": 52.55,
            "total_trades": 274,
        },
        "raw": {
            "execution_price_basis": "raw_ohlc_pre_close",
            "total_return_pct": 172.37,
            "gross_return_pct": 227.44,
            "max_drawdown_pct": 13.53,
            "win_rate_pct": 51.82,
            "total_trades": 274,
        },
        "delta_raw_minus_adjusted": {
            "total_return_pp": -29.32,
            "gross_return_pp": -33.42,
            "max_drawdown_pp": 0.01,
            "total_pnl": -146603.05,
            "gross_pnl": -167102.82,
            "total_costs": -20499.78,
        },
        "overlap": {
            "adjusted_trades": 274,
            "raw_trades": 274,
            "common_entry_code": 274,
            "adjusted_only": 0,
            "raw_only": 0,
            "same_exit_date": 274,
            "same_exit_reason": 274,
        },
        "matched_trade_sums": {
            "pnl_adjusted": 1008459.88,
            "pnl_raw": 861856.83,
            "pnl_delta_raw_minus_adjusted": -146603.04,
            "notional_effect": -74987.79,
            "return_effect": -71615.26,
        },
    },
}
